version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.2-browsers-legacy
        environment:
          NO_SANDBOX: true
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm run lint
      - run:
          command: npm run build
